### ISSUE TITLE
invalid characters in Cheung 2018-related files

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/moinput#33]
```
── R CMD check results ──────────────────────────────────── moinput 9.297.0 ────
Duration: 3m 37.5s

> checking R files for non-ASCII characters ... WARNING
  Found the following files with non-ASCII characters:
    calcFishCCImpactCheung2018.R
    calcFishCCImpactCheung2018Aqua.R
    readCheung2018.R
  Portable packages must use only ASCII characters in their R code,
  except perhaps in comments.
  Use \uxxxx escapes for other characters.

0 errors ✓ | 1 warning x | 0 notes ✓
Error: R CMD check found WARNINGs
```

Offending characters are "ï", "ã§", and "é".
<pre><font color="#EEE8D5">$</font> grep --color=&apos;auto&apos; -P -n &quot;[\x80-\xFF]&quot; R/calcFishCCImpactCheung2018.R R/calcFishCCImpactCheung2018Aqua.R R/readCheung2018.R
<font color="#D33682">R/calcFishCCImpactCheung2018.R</font><font color="#2AA198">:</font><font color="#859900">39</font><font color="#2AA198">:</font>    x_ModelOutputDBEM &lt;- toolAggregate(x_ModelOutputDBEM, rel=relationmatrix, from=&quot;Scenarios&quot;, to=&quot;<font color="#DC322F"><b>ï</b></font>..FAO.Fishing.Area&quot;, weight=w, dim=3.1)
<font color="#D33682">R/calcFishCCImpactCheung2018.R</font><font color="#2AA198">:</font><font color="#859900">110</font><font color="#2AA198">:</font>    x_ModelOutputDynModel &lt;- toolAggregate(x_ModelOutputDynModel, rel=relationmatrix, from=&quot;Scenarios&quot;, to=&quot;<font color="#DC322F"><b>ï</b></font>..FAO.Fishing.Area&quot;, weight=w, dim=3.1)
<font color="#D33682">R/calcFishCCImpactCheung2018Aqua.R</font><font color="#2AA198">:</font><font color="#859900">42</font><font color="#2AA198">:</font>    x_ModelOutputDBEM &lt;- toolAggregate(x_ModelOutputDBEM, rel=relationmatrix, from=&quot;Scenarios&quot;, to=&quot;<font color="#DC322F"><b>ï</b></font>..FAO.Fishing.Area&quot;, weight=w, dim=3.1)
<font color="#D33682">R/calcFishCCImpactCheung2018Aqua.R</font><font color="#2AA198">:</font><font color="#859900">137</font><font color="#2AA198">:</font>    x_ModelOutputDynModel &lt;- toolAggregate(x_ModelOutputDynModel, rel=relationmatrix, from=&quot;Scenarios&quot;, to=&quot;<font color="#DC322F"><b>ï</b></font>..FAO.Fishing.Area&quot;, weight=w, dim=3.1)
<font color="#D33682">R/readCheung2018.R</font><font color="#2AA198">:</font><font color="#859900">44</font><font color="#2AA198">:</font>    &quot;cura<font color="#DC322F"><b>ã§</b></font>ao&quot;=&quot;CUW&quot;, 
<font color="#D33682">R/readCheung2018.R</font><font color="#2AA198">:</font><font color="#859900">93</font><font color="#2AA198">:</font>    &quot;r<font color="#DC322F"><b>é</b></font>union&quot;=&quot;REU&quot;,
<font color="#D33682">R/readCheung2018.R</font><font color="#2AA198">:</font><font color="#859900">100</font><font color="#2AA198">:</font>    &quot;saint barth<font color="#DC322F"><b>é</b></font>lemy&quot;=&quot;BLM&quot;,
</pre>

Also, the `Version` number has not been increased since 062bbac89e93ba978eac65717c01764cf9dddcfd.
https://github.com/pik-piam/moinput/blob/345ea4b643192b1d9cf04270d0e861b1f3e8599d/DESCRIPTION#L4

Can't assign [wehnerja](https://github.com/wehnerja), not in [PIAM](https://github.com/orgs/pik-piam/people).

**Comment by giannou** [comment]
I invited him to PIAM but he's not accepting the invitation. We can also revert the commits

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@wehnerja to restore the (broken) state of your changes and work on them, run this in the git shell:
```
git diff --patch 5f71c3f..345ea4b > patch.txt
patch -p1 < patch.txt
rm patch.txt
```
Then the issues can be fixed.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@giannou we need better onboarding.  It looks to me as if nobody told [wehnerja](https://github.com/wehnerja) about `buildLibrary.R` that it is to be used.  Also #21 please! ;)

**Comment by wehnerja** [comment]
Sorry for being so unresponsive. Would it be still possible to revert my commits now? The issues have been fixed by Marcos Paulo Pedrosa Alves.

**Comment by wehnerja** [comment]
Sorry for being so unresponsive. The issues have been fixed by a Marcos Paulo Pedrosa Alves, already committed and a pull request has been sent. As there is no need to restore my changes anymore, I will not execute the code you have sent to me in the git shell. Sorry for causing any inconvenience.

**Comment by k4rst3ns** [comment]
hey guys, 

could you please be a bit more patient with reverting the next time? Bugfix was on its way and it was much more complicated now with your interference.

Maybe if someone is not responding via github (new workflow, we all have to get used to it, not everybody is included in it like student helpers), maybe trying to get in touch via (old-school) mail would be really nice for the transition phase. The bugfix was already made, when you were reverting the commits, it was just not pushed. And we struggled a bit with getting everything back in (which was also related to our workflow).

@michaja: your patch solution probably works, but why we are not just use a revert of your revert commit to undo it? Since most of us are familiar with git commands, but probably not all of us with the idea of 'patch', your solution looks like a black box to most of us.

**Comment by giannou** [comment]
Hi,

Please keep your request for more patience in mind next time you write us emails with a note "it would be nice if [add here whatever issue] was solved quickly" :) 

moinput, madrat and magclass are too important for the work of ~60 people to be broken for long.

Also, we tried to contact wehnerja and didn't manage to find their email (not in their profile), so how exactly do you suggest we contact them?

Cheers

**Comment by k4rst3ns** [comment]
Hey you,

I know that it is critical, but it was broken so many times before without being reverted.
My feeling was so far that is was not the normal workflow to revert bugs, but rather fix them quickly.

When you were on her profile, you could see that she also had a fork of MAgPIE and LPJmL and probably would have guessed that, she or somebody who would take care of it might be part of at least magpie-list. Also her name is in the author item of the functions you reverted.

I do not want to make bad mood, I totally see you point and just wanted to point out, that github issues are so far not really established in our workflow (unfortunately). It was a bit funny that our communication, was totally independent of yours (Benni spotted the issue just some hours after the push and send an sos mail to all people involved from our side. You reverted it basically in the moment Marcos wanted to push his bugfix). 

cheers, kristine

PS: maybe since it is now solved and back in the game, we can close the issue ^^'

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> your patch solution probably works, but why we are not just use a revert of your revert commit to undo it? Since most of us are familiar with git commands, but probably not all of us with the idea of 'patch', your solution looks like a black box to most of us.

Tomato – tomato.  If you (or anybody else) knows git commands, use them.  If you don't know them, `patch`ing is straight forward, doesn't give you git warnings and leaves the directory in a recognisable state from which you can proceed.

>  My feeling was so far that is was not the normal workflow to revert bugs, but rather fix them quickly.

This bug had no business being in the package in the first place.  The normal workflow is to run `buildLibrariy.R` first, which would have prevented this commit from being made at all. 

Which leads back to 
> we need better onboarding. It looks to me as if nobody told @wehnerja about `buildLibrary.R` and that it is to be used. Also #21 please!
